

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "现代密码学实验" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "jeza@vip.qq.com"
description: >- # this means to ignore newlines until "baseurl:"
author: name
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1